server:
  port: 12200

spring:
  application:
    name: test-server
  output:
    ansi:
      enable: ALWAYS

logging:
  path: ./log
  level:
    com:
      alipay:
        test: INFO

com:
  alipay:
    sofa:
      rpc:
        registry:
          address: nacos://k8s-default-nacosser-349c7af5d9-fbbb76f615085720.elb.us-west-2.amazonaws.com:8848
          local:
            Zone: DEFAULT